### ISSUE TITLE
No cancela facturas timbradas por finkok

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1542]
Es uno de los clientes que está alambrado para que se vaya por finkok.
Es del conector.
El rfc es EPN010312GC0
Y la factura es la num 28600
intentamos cancelarla ayer, y marcó error

**Comment by jccastillo0007** [comment]
Vi el log, y encontre este error 

2019-05-06 14:33:35,744 ERROR [http-nio-8080-exec-9] (SealerPACProcess.java:296) - java.io.FileNotFoundException: /FacturaTi/PAC/FactureHoy/EPN010312GC0.pfx (Permission denied)
java.io.FileNotFoundException: /FacturaTi/PAC/FactureHoy/EPN010312GC0.pfx (Permission denied)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at com.facturati.ws.controller.SealerPACProcess.processCancelOtherPAC(SealerPACProcess.java:291)
        at com.facturati.ws.controller.SealerPACProcess.processFactureHoyCancel(SealerPACProcess.java:254)
        at com.facturati.ws.controller.Sealer.processCancelCFDiFirstApproach(Sealer.java:437)


El archivo pfx no tenia los permisos adecuados... debe  tener 755 y solo tenia 400.

Le di permisos a ese archivo y a todos los demás, hay que ver como se suben esos archivos

**Comment by RigoFlores** [comment]
Evidentemente el procedimiento para subir los archivos es el mismo. 
Cada mes se suben varios archivos.
Solo déjame entender, la cancelación solo se ejecuta por fhoy, correcto?
Hay diferencia en el servicio que se ocupa cuando la factura a cancelar es de fhoy o de finkok?

**Comment by RigoFlores** [comment]
De hecho con ese RFC, si no mal recuerdo, lo he tenido que subir varias ocasiones... lo cual podría implicar que el nombre del archivo, quizás sea el problema....

**Comment by jccastillo0007** [comment]
si, para cancelar se usa fhoy en ambos casos, primero se intenta el web service normal de cancelar y luego el de cancelar facturas timbradas por finkok.
el problema era los permisos no el nombre

**Comment by RigoFlores** [comment]
Me refiero a que en particular con ese RFC se han tenido recurrentes problemas al cancelar.
Entiendo que es por los permisos.
Lo que sospecho, es que el nombre del archivo, de alguna manera podría ser de uso restringido o parecido al nombre de un archivo de sistema. Y por ello le está cambiando los permisos... es lo único que se me ocurre.
