### ISSUE TITLE
Escritorio CFDI 4.0 - Implementar cancelación 2022

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1955]
En este caso, que el CFDI relacionado lo puedan buscar o si se complica, que lo tecleen.

**Comment by jccastillo0007** [comment]
sería en la misma modal que se abre para cancelar hoy en día cierto?

Ahi solo pondré las opciones de motivo cancelación y cfdi relacionado, tendrán que teclearlo

**Comment by RigoFlores** [comment]
Afirmativo.

**Comment by jccastillo0007** [comment]
fixed

**Comment by jccastillo0007** [comment]
pero no se puede probar en pru

**Comment by RigoFlores** [comment]
levanté apuntando a pro...
pero no da chance de capturar un id relacionado.
por otro lado, marcó error, yo creo que no lo hizo... este es el error..

2022-03-18 14:19:47,630 DEBUG [AWT-EventQueue-0] (DeliveryPathCreator.java:327) - looking for XML at folder : C:\Conector3.3Produccion\FACTURAS\mar2022\XML fi
les in folder : 1
2022-03-18 14:19:47,632 DEBUG [AWT-EventQueue-0] (DeliveryPathCreator.java:331) - looking for XML filename starts with : BORRAR16_XAXX010101000_18mar2022_1406

2022-03-18 14:19:48,009 ERROR [AWT-EventQueue-0] (JaxbXMLProvider.java:191) - javax.xml.bind.UnmarshalException: unexpected element (uri:"http://www.sat.gob.m
x/cfd/3", local:"Comprobante"). Expected elements are <{http://www.sat.gob.mx/cfd/4}Comprobante>
javax.xml.bind.UnmarshalException: unexpected element (uri:"http://www.sat.gob.mx/cfd/3", local:"Comprobante"). Expected elements are <{http://www.sat.gob.mx/
cfd/4}Comprobante>
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:647)
        at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:258)
        at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:253)
        at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:120)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1052)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:483)

**Comment by RigoFlores** [comment]
ya lo revisé en el sat y no, no está cancelado.

**Comment by RigoFlores** [comment]
si quieres las facturas a cancelar, aquí están...
[PAGO15_XAXX010101000_18mar2022_142653.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/8307468/PAGO15_XAXX010101000_18mar2022_142653.zip.txt)
