### ISSUE TITLE
las barricas - envio de correo de falla al procesar el archivo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2084]
Existen 3 tipos de correos:

a) El de la llave del conector (emisor).
b) El correo del receptor
c) El correo en caso de falla al timbrar 

Cuando falla el procesamiento, ÚNICAMENTE SE DEBE ENVIAR AL CORREO (c)
Cuando se procesa correctamente la factura, SE ENVÍA AL RECEPTOR Y AL EMISOR (a y b).

Ahora mismo, ya sea con falla o timbrada correctamente, lo envía al correo (a) y (b)

La leyenda que estamos ocupando es :

eMailError=

**Comment by jccastillo0007** [comment]
fixed, con la versión de hoy.

**Comment by RigoFlores** [comment]
En caso de falla, si, ya envía el correo a la cuenta definida para dicho fin.
Pero lo está enviando 2 veces al mismo correo.
Eso confundirá al cliente.

Tiene que enviarla solo una vez a esa cuenta.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
pues ahora ya no lo envía. Marca esto:

2023-01-10 09:45:38.0312 ERROR pool-3-thread-1 com.facturat.controller.flatfile.ConnectorReader For input string: "" 
2023-01-10 09:45:38.0312 DEBUG pool-2-thread-1 com.facturat.controller.flatfile.ConnectorReader EMAILS TO : contacto@factura-t.com.mx 
2023-01-10 09:45:38.0312 ERROR pool-3-thread-1 com.facturat.controller.flatfile.ConnectorReader invalid file : C:\Conector4.0\CONECTOR\TPPM026725.txt 
2023-01-10 09:45:38.0320 ERROR pool-2-thread-1 com.cfd.shared.utils.EmailService java.lang.NullPointerException 
java.lang.NullPointerException
	at com.facturat.emailing.SendInvoiceOrCancelInvoiceToReceptor.sendEmailInvoiceError(SendInvoiceOrCancelInvoiceToReceptor.java:785)
	at com.cfd.shared.utils.EmailService.sendEmailError(EmailService.java:56)
	at com.facturat.controller.flatfile.ConnectorReader$2.run(ConnectorReader.java:378)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2023-01-10 09:45:38.0320 DEBUG pool-2-thread-1 com.facturat.controller.flatfile.ConnectorReader Problemas para enviar el CFDi por correo
