### ISSUE TITLE
Implementar nueva instancia de Plataforma de Facturación para Clientes - restaurante Galpón

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2246]
En este caso existirán 2 layouts distintos para la misma URL. Una para el restaurante y otra para el hotel.
El restaurante se llama El Galpón.

Requerimiento: Trabajar el conector que procese el layout anexo.

El archivo a procesar,  se genera a partir de su software punto de venta.
Aquí tienes ejemplo del archivo, así como su mapeo para ser procesado.

[mapeoArchivo.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/12822325/mapeoArchivo.zip.txt)

Hay que levantar la instancia de la plataforma de facturación.
El ticket en la pantalla de autofacturación, se buscará por ID y total del ticket.

**Comment by jccastillo0007** [comment]
El archivo csv trae muchos registros, que mencionas que son los productos... 
dices que el primer campo es el folio, que es único e irrepetible, y con ese buscarán el ticket para facturarlo, pero luego dices que también es el id del producto.
Entonces cada renglón es un ticket ? es decir, cada ticket tendrá un producto ?

Si tienen mas de uno, que id usarán para encontrar el ticket y facturar?

**Comment by jccastillo0007** [comment]
Según el archivo de word, cada renglón es un concepto:

VIII.	A nivel concepto, por cada renglón en el archivo:
a)	Concepto: consumo de alimentos
b)	Cantidad: 1
c)	Unidad: E48. Servicio
d)	Clave SAT:  
e)	ID, igual al número de ticket

Entonces, cómo encontraran el ticket si tiene multiples ids ?

**Comment by RigoFlores** [comment]
> El archivo csv trae muchos registros, que mencionas que son los productos... dices que el primer campo es el folio, que es único e irrepetible, y con ese buscarán el ticket para facturarlo, pero luego dices que también es el id del producto. Entonces cada renglón es un ticket ? es decir, cada ticket tendrá un producto ?
> 
> Si tienen mas de uno, que id usarán para encontrar el ticket y facturar?

Cada renglón es un ticket. Cada ticket tendrá un solo producto, que será "CONSUMO DE ALIMENTOS".
El ID del ticket será único e irrepetible en el caso del restaurante, servirá para buscar el ticket. Además el ID ticket, servirá como ID del único producto del ticket (así como en abastos).

**Comment by jccastillo0007** [comment]
chiaaa ok

**Comment by RigoFlores** [comment]
> Según el archivo de word, cada renglón es un concepto:
> 
> VIII. A nivel concepto, por cada renglón en el archivo: a) Concepto: consumo de alimentos b) Cantidad: 1 c) Unidad: E48. Servicio d) Clave SAT: e) ID, igual al número de ticket
> 
> Entonces, cómo encontraran el ticket si tiene multiples ids ?

Estos datos son fijos. No vienen en los registros del archivo de texto (renglones).
Para el restaurante, el ID es único. El ID también será el ID del producto, dentro del nodo de concepto.

**Comment by RigoFlores** [comment]
Del archivo tomaremos 
el ID ticket (para búsqueda) y que servirá como ID del producto en el nodo concepto (NoIdentificacion="ID ticket").
Total. El total con IVA de ese ticket.
Forma de pago: dependiendo de la columna con el dato mas grande, será la forma de pago.

solamente son 3 datos que se tomarán del archivo.

lo demás son datos fijos y/o que se calcularán al vuelo.

tienes duda en esto???

**Comment by jccastillo0007** [comment]
ya se están subiendo los archivos correctamente

**Comment by RigoFlores** [comment]
Se tenía un detalle con el archivo al guardarlo como CVS+UFT8, pero si se guarda solo como csv ya no le pone unos caracteres al inicio. De hecho creo que el estándar UTF8 requiere de esos caracteres. 
Pero ya, al guardarlo como csv únicamente, ya queda limpio el archivo.

Aún así, no lo procesa desde mi computadora. El error sigue siendo el mismo:


2023-10-14 07:58:05.0354 DEBUG pool-1-thread-1 com.facturat.controller.flatfile.ConnectorReader FLAT FILE CONNECTOR is still running : true 
2023-10-14 07:58:05.0354 INFO pool-1-thread-1 com.facturat.controller.flatfile.ConnectorReader  file to be processed : C:\ConectorNuevo\Conector\051023-1.csv 
2023-10-14 07:58:05.0354 DEBUG pool-1-thread-1 com.facturat.controller.flatfile.ConnectorProcessorGalpon Processing this ticket : 6279.00,250.00,0.00,0.00,250.00,0.00 
2023-10-14 07:58:05.0354 DEBUG pool-1-thread-1 com.facturat.controller.flatfile.ConnectorProcessorGalpon Serie : null  Folio : 6279.00 Total : 250.0 
2023-10-14 07:58:05.0369 DEBUG pool-1-thread-1 com.facturat.controller.flatfile.ConnectorProcessorGalpon URL: http://efacturat-stagging.com.mx:8080/efacturat-api/private/efacturat-api/invoicing/createCFDi 
2023-10-14 07:58:05.0369 DEBUG pool-1-thread-1 com.facturat.controller.flatfile.ConnectorProcessorGalpon Sending request : {"sourceName":null,"sourceRFC":"IIA040805DZ4","sourceRegimen":null,"sourceRegimenKey":null,"targetEmails":null,"targetName":null,"targetRFC":null,"targetZipcode":null,"targetRegimen":null,"targetRegimenKey":null,"CFDiusage":null,"CFDiusageKey":null,"paymentType":"08","paymentMethod":"PUE","paymentConditions":null,"CFDiType":"I","CFDiName":"Factura","serie":null,"folio":"6279.00","id":"6279.00","currency":"MXN","currencyRate":1.0,"typeRelationship":null,"typeRelationshipKey":null,"CFDiRelationship":null,"globalPeriodicity":null,"globalMonth":null,"globalYear":null,"products":[{"unit":"Servicio","unitId":"E48","quantity":1.0,"price":null,"productId":"6279.00","productIdSat":"90101501","amount":250.0,"additionalInformation":"consumo de alimentos","includeComplementaryInformationInTheXML":null,"propertyAccount":null,"entrySummary":null,"discountPercentage":0,"discount":0.0,"discountReason":null,"subtotal":215.51724137931035,"total":250.0,"extradata":[],"ivabasedieps":null,"withheldTaxes":[],"transferredTaxes":[{"tax":"IVA","amount":34.48275862068965,"price":0.16,"factor":"Tasa","baseTax":0.0,"type":"Trasladado"}],"extradataAsString":"[]","allTaxesAsString":"[{\"amount\":34.48275862068965,\"baseTax\":0,\"factor\":\"Tasa\",\"price\":0.16,\"tax\":\"IVA\",\"type\":\"Trasladado\"}]"}],"withheldTaxes":null,"transferredTaxes":[{"tax":"IVA","amount":34.48275862068965,"price":0.16,"factor":"Tasa","baseTax":0.0,"type":"Trasladado"}],"subtotal":215.51724137931035,"discounts":0.0,"subtotalMinusDiscounts":0.0,"totalTransferredTaxes":34.48275862068965,"totalWithheldTaxes":0.0,"total":250.0,"sendToTarget":false,"sendToSource":false,"taxLegendSupplement":false,"foreignTradeSupplement":false,"constructionSupplement":false,"saveAsRecurringDate":false,"safeForLater":true,"recurringDate":null,"extradata":null,"date":null,"export":null,"SATstatus":null,"CxCstatus":null,"CxPstatus":null,"expirationDate":null,"isPaid":false,"creditDays":0,"creditAmount":0.0,"pathCBB":null,"pathLogo":null,"certifiedNumber":null,"originalStream":null,"digitalSigned":null,"pacness":null,"folioSAT":null,"certifiedNumberSAT":null,"timbreDate":null,"timbreSAT":null,"pacRFC":null,"satstatus":null,"cxCstatus":null,"cxPstatus":null,"cfdiusageKey":null,"paid":false,"cfdiRelationship":null,"extradataAsString":"[null]","allTaxesAsString":"[{\"amount\":34.48275862068965,\"baseTax\":0,\"factor\":\"Tasa\",\"price\":0.16,\"tax\":\"IVA\",\"type\":\"Trasladado\"}]","cfdiType":"I","cfdiusage":null,"cfdiName":"Factura","relatedCFDiAsString":"[null]"} 
2023-10-14 07:58:05.0776 ERROR pool-1-thread-1 com.facturat.controller.flatfile.ConnectorReader java.lang.RuntimeException: Failed : HTTP error code : 500 
java.lang.RuntimeException: Failed : HTTP error code : 500
	at com.facturat.controller.flatfile.ConnectorProcessorGalpon.createCFDi(ConnectorProcessorGalpon.java:165)
	at com.facturat.controller.flatfile.ConnectorProcessorGalpon.processFile(ConnectorProcessorGalpon.java:114)
	at com.facturat.controller.flatfile.ConnectorReader.fileAnalyzer(ConnectorReader.java:178)
	at com.facturat.controller.flatfile.ConnectorReader.run(ConnectorReader.java:111)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by RigoFlores** [comment]
Yo creo que mientras sigamos desarrollando y probando en ambientes distintos, nos enfrentaremos a esto que tanto nos retrasa.
Los clientes, la mayoría si no es que todos, tienen windows.

**Comment by jccastillo0007** [comment]
fixed
