### ISSUE TITLE
PFTv1.0 - complemento de pago, marca error al intentar timbrar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2370]
La petición de timbrado no se ejecuta, ya que antes se genera este error.
Esto a partir del cambio que subimos anoche.

2024-02-06 11:13:01,275 DEBUG [https-jsse-nio-8443-exec-3] (CxCNewPagosPanel.java:1140) - hashtable base from hashtable : null
2024-02-06 11:13:01,275 DEBUG [https-jsse-nio-8443-exec-3] (CxCNewPagosPanel.java:1466) - RelatedDocuments : {b73b5e78-05c9-4236-9170-9be8191700dd|F|8509|MXN|1.0|PPD|1|889.9999999999999|890.0|-1.1368683772161603E-13Traslados{[122.75862100000002|002|16.0|Tasa|767.2413812500001],}Retenidos{}
2024-02-06 11:13:01,276 ERROR [https-jsse-nio-8443-exec-3] (DefaultExceptionMapper.java:114) - Unexpected error occurred
org.apache.wicket.WicketRuntimeException: Method onRequest of interface org.apache.wicket.behavior.IBehaviorListener targeted at com.efacturat.view.panel.CxCNewPagosPanel$39 {event='onClick'} on component [Component id = executeImage] threw an exception

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
no, ahora marca otro error, es como de las rutas o no se que cosa...
Error al crear XML (100)

2024-02-06 21:43:37,085 DEBUG [https-jsse-nio-8443-exec-15] (XML_AddendaTypes.java:71) - looking addenda for : TIA101020BP4
2024-02-06 21:43:37,086 DEBUG [https-jsse-nio-8443-exec-15] (XML_AddendaTypes.java:71) - looking addenda for : QUFA580714162
2024-02-06 21:43:37,086 DEBUG [https-jsse-nio-8443-exec-15] (CFDManager.java:204) - Source is addendable and will add : null
2024-02-06 21:43:37,086 DEBUG [https-jsse-nio-8443-exec-15] (CFDManager.java:205) - Target is addendable and will add : null
2024-02-06 21:43:37,087 DEBUG [https-jsse-nio-8443-exec-15] (CFDManager.java:244) - XML creates type : PAGOS  0.0
2024-02-06 21:43:37,087 DEBUG [https-jsse-nio-8443-exec-15] (JaxbXMLProvider.java:46) - Setup JaxbManager
2024-02-06 21:43:37,102 DEBUG [https-jsse-nio-8443-exec-15] (JaxbXMLProvider.java:64) - create new XMLCFD type : com.cfd.xml.provider.jaxb.cfdi_v40.Comprobante
2024-02-06 21:43:37,104 ERROR [https-jsse-nio-8443-exec-15] (CFDBusinessLogicProvider.java:118) - java.lang.NullPointerException
java.lang.NullPointerException
        at com.cfd.xml.provider.jaxb.cfdi_v40.Comprobante.setup(Comprobante.java:319)

**Comment by jccastillo0007** [comment]
fixed, ya debería funcionar...

**Comment by RigoFlores** [comment]
en pantalla marca error al crear el XML (100)
en catalina se incluye lo siguiente...

2024-02-07 07:12:00,703 DEBUG [https-jsse-nio-8443-exec-2] (XML_AddendaTypes.java:71) - looking addenda for : TIA101020BP4
2024-02-07 07:12:00,706 DEBUG [https-jsse-nio-8443-exec-2] (XML_AddendaTypes.java:71) - looking addenda for : QUFA580714162
2024-02-07 07:12:00,707 DEBUG [https-jsse-nio-8443-exec-2] (CFDManager.java:204) - Source is addendable and will add : null
2024-02-07 07:12:00,707 DEBUG [https-jsse-nio-8443-exec-2] (CFDManager.java:205) - Target is addendable and will add : null
2024-02-07 07:12:00,707 DEBUG [https-jsse-nio-8443-exec-2] (CFDManager.java:244) - XML creates type : PAGOS  0.0
2024-02-07 07:12:00,708 DEBUG [https-jsse-nio-8443-exec-2] (JaxbXMLProvider.java:46) - Setup JaxbManager
2024-02-07 07:12:00,762 DEBUG [https-jsse-nio-8443-exec-2] (JaxbXMLProvider.java:64) - create new XMLCFD type : com.cfd.xml.provider.jaxb.cfdi_v40.Comprobante
2024-02-07 07:12:00,763 ERROR [https-jsse-nio-8443-exec-2] (CFDBusinessLogicProvider.java:118) - java.lang.NullPointerException
java.lang.NullPointerException
        at com.cfd.xml.provider.jaxb.cfdi_v40.Comprobante.setup(Comprobante.java:319)

**Comment by RigoFlores** [comment]
ya está en  pru, favor de subir a pro...
