### ISSUE TITLE
Conector Las Barricas - no está enviando el correo,  en caso de que el archivo de texto venga con error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2430]
La última versión, la de carta porte 3.0 es la que inyectó este problema.
Si intento levantar con jdk 8, no levanta.
Y con la versión 7, marca error donde debería enviar el correo:

2024-05-15 15:27:11.0801 INFO pool-3-thread-1 com.facturati.ws.client.CFDiWSClient FacturaTi ack : com.facturati.ws.binding.jaxb.Ack@344122b9[code=003,description=CFDI40144 : El campo Nombre del receptor, debe encontrarse en la lista de RFC inscritos no cancelados en el SAT.] 
2024-05-15 15:27:11.0802 DEBUG pool-3-thread-1 com.facturati.ws.client.CFDiWSClient Properties received : CFDi_FOLIO value : 14872 
2024-05-15 15:27:11.0807 ERROR pool-3-thread-1 com.facturat.controller.flatfile.ConnectorReader For input string: "" 
2024-05-15 15:27:11.0814 DEBUG pool-2-thread-1 com.facturat.controller.flatfile.ConnectorReader EMAILS TO : soporte@factura-t.com.mx 
2024-05-15 15:27:11.0815 ERROR pool-3-thread-1 com.facturat.controller.flatfile.ConnectorReader invalid file : C:\Conector4.0\CONECTOR\LVF002162.txt 
2024-05-15 15:27:11.0820 ERROR pool-2-thread-1 com.facturat.controller.flatfile.ConnectorReader java.lang.NullPointerException 
java.lang.NullPointerException
	at com.facturat.controller.flatfile.ConnectorReader$2.run(ConnectorReader.java:437)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Aquí te dejo la llave y el archivo de texto
[facturaT_XIQB891116QE4.cfdi.LasBarricas.txt](https://github.com/jccastillo0007/eFacturaT/files/15327212/facturaT_XIQB891116QE4.cfdi.LasBarricas.txt)
[LVF002162.txt](https://github.com/jccastillo0007/eFacturaT/files/15327213/LVF002162.txt)

**Comment by RigoFlores** [comment]
De hecho, no debe estar enviando ningún correo.
Por los mensajes de la consola, no está jalando el envio del correo en genral.

**Comment by jccastillo0007** [comment]
fixed, probar con la versión 15.0.7 y con java 7

**Comment by RigoFlores** [comment]
No, no jaló... con la versión 7.0 del jdk

**Comment by jccastillo0007** [comment]
puedes checar con la versión 15.0.9

**Comment by RigoFlores** [comment]
Sigue igual que la versión anterior, marca esto en la consola DOS:

com.mx/eFacturaT/logo_facebook.png" width=3D"50" height=3D"50"></a></td><td=
 rowspan=3D"3"><a href=3D"https://www.youtube.com/user/FacturaT2014" target=
=3D"_blank"><img src=3D"https://efacturat.com.mx/eFacturaT/logo_youtube.png=
" width=3D"50" height=3D"50"><java.io.FileNotFoundException: LVF002162.txt (The system cannot find the file specified)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
        at javax.activation.DataHandler.writeTo(DataHandler.java:305)
        at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1403)
        at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:874)
        at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:444)
        at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:102)
        at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
        at javax.activation.DataHandler.writeTo(DataHandler.java:317)
        at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1403)
        at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1745)
        at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:636)
        at com.facturat.emailing.SendInvoiceOrCancelInvoiceToReceptor.sendEmailInvoiceTOReceptor(SendInvoiceOrCancelInvoiceToReceptor.java:700)
        at com.cfd.shared.utils.EmailService.sendEmailError(EmailService.java:56)
        at com.facturat.controller.flatfile.ConnectorReader$2.run(ConnectorReader.java:450)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2024-05-20 12:00:01,296 ERROR [pool-2-thread-1] (SendInvoiceOrCancelInvoiceToReceptor.java:709) - javax.mail.MessagingException: IOException while sending mes
sage;
  nested exception is:
        java.io.FileNotFoundException: LVF002162.txt (The system cannot find the file specified)
javax.mail.MessagingException: IOException while sending message;

**Comment by jccastillo0007** [comment]
fixed, release 15.0.1 de hoy 20 de Mayo

**Comment by RigoFlores** [comment]
ya lo está enviando ahora si.
Puedes comentar que fue lo que resolvió el tema, para en un futuro no nos cueste tanto trabajo?

**Comment by jccastillo0007** [comment]
Inicialmente fue la versión de Java que solo se soporta la 1.7 , eventualmente tal vez tenga que cambiar eso
Luego fue el tema del archivo, que lo mueve a fallados antes de enviar el email y por eso no lo encuentra
