### ISSUE TITLE
Ajustar conector para demo JMAS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2471]
Este sería el Layout para este conector de demo:

ID ticket columna A,
Total: columna E

Descripción "Pago de servicios de agua número de cuenta "columna C" del usuario  "columna D" 

Solo desglosa el IVA del 16% y es todo

[JASC.csv](https://github.com/user-attachments/files/16808237/JASC.csv)

**Comment by jccastillo0007** [comment]
Listo, subí el release FacturaT_JMAS_14.0.1.zip. al dropbox... con ese puedes subir el archivo que me enviaste....

usa el RFC IIA que era de galpon, así que no te vayas a confunidr.... 

Después de subirlos, los puedes facturar con el aft de galpon

**Comment by RigoFlores** [comment]
no levanta con la misma versión de java que tenía la versión anterior del conector.
acaso ahora ya cambió la versión de java que se requiere???

Si la cambio, los otros conectores se harán un desmadre.
Además el galpón es uno de los conectores que mas tenemos que probar, en todo caso se hubiera tomado el de virtual homes que es el más estable de todos.

**Comment by RigoFlores** [comment]
marca esto:


Exception in thread "main" java.lang.UnsupportedClassVersionError: com/facturat/view/FacturaT : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by jccastillo0007** [comment]
ya lo volvía compilar con java 8 y lo subí con el nombre: FacturaT_JMAS_14.0.2.zip

**Comment by RigoFlores** [comment]
oye, pero con cuál versión estabas trabajando?
Debemos homologar una misma versión, si no es un desmadre.

procesé el archivo completo y si tomó casi todas las remisiones, pero el primer registro no lo está encontrando.

**Comment by jccastillo0007** [comment]
no tiene caso, lo arreglamos ya que compren el conector

**Comment by RigoFlores** [comment]
¿cuál sería el layout para un archivo con varios renglones?
Y no debe ser el estándar de conector 1.0, ya que ese incluye mucha información que no se ocupa en este caso.

básicamente podría ser descripción, subtotal, impuestos, total (por cada producto)
Hoy se tiene esto:

1316564,50413,5601041388,ERNESTO ALONSO MERAZ CORRAL,187    


Sugiero lo siguiente:
1316564,50413,5601041388,ERNESTO ALONSO MERAZ CORRAL, DESCRIPCION1, CONIVA, 187    
1316564,50413,5601041388,ERNESTO ALONSO MERAZ CORRAL, DESCRIPCION2, CONIVA, 187    
1316564,50413,5601041388,ERNESTO ALONSO MERAZ CORRAL, DESCRIPCION3, CONIVA, 187    
1316564,50413,5601041388,ERNESTO ALONSO MERAZ CORRAL, DESCRIPCION4, SINIVA, 187    

ALGO así para un ticket con varios productos, cómo vex?

**Comment by RigoFlores** [comment]
Con el layout anterior, todos los renglones que compartan en mismo número de ticket, se incluirán en ese ID cuando sea invocado desde AFT.
Adicionalmente la aplicación tendrá que sumar los importes, desglosando los impuestos correspondientes cuando aplique.
En este caso es IVA 16% o IVA exento.

Solo confirma que estás de acuerdo para mañana comentarle al cliente.

**Comment by jccastillo0007** [comment]
se ve bien, habrá que esperar a hacer pruebas para ver ajustes
