### ISSUE TITLE
ESCRITORIO - SOPORTAR LOS ENTER EN LA DESCRIPCIÓN, ASÍ COMO EN WEB

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#305]
EN WEB, SI TECLEAMOS ENTERS Y ESPACIOS EN LA DESCRIPCIÓN (EL CUADRO GRANDE DENTRO DEL CATÁLOGO DE PRODUCTOS), RESPETA LOS ENTERS, AUNQUE AL XML, LOS CAMBIA POR CARACTERES RAROS.
ESO MISMO HACERLO EN ESCRITORIO PARA LA DESCRIPCIÓN, ESTO ES PARA QUE LO QUE CAPTURES TAL CUAL SE REFLEJE EN EL PDF, PERO EN EL XML SE VEA 'CORRIDO'.

**Comment by jccastillo0007** [comment]
Fixed.

Checa el xml y pdf, ambos tienen <enter> en la descripción tanto del producto como complementaria

![screen shot 2015-01-27 at 8 39 40 am](https://cloud.githubusercontent.com/assets/2245679/5920170/17045bfc-a600-11e4-8cad-f871507de87a.png)
![screen shot 2015-01-27 at 8 39 29 am](https://cloud.githubusercontent.com/assets/2245679/5920185/2ed58c88-a600-11e4-8c93-a51cf4e6d5ce.png)

**Comment by RigoFlores** [comment]
en web si, pero en escritorio así no lo veo....

**Comment by jccastillo0007** [comment]
Fixed.

Release 9.1.1 en jenkins, te mande la liga por email.

**Comment by RigoFlores** [comment]
Intenté levantar con la nueva versión, y una BD que ya tengo de hace tiempo y marca lo siguiente... no pudo levantar..

2015-02-03 10:31:59,586 DEBUG [main](FacturaT.java:134) - Initializing FacturaT

2015-02-03 10:31:59,722 DEBUG [main](EmisorController.java:46) - we found the k
ey : facturaT_XAXX010101000_extraData.cfdi
2015-02-03 10:31:59,890  INFO [main](EmisorController.java:113) - JSON KEY :{"a
ddress":{"country":"MEXICO","locale":"","municipio":"QUERETARO","name":"","neigh
bourhood":"CONSTITUYENTES","number_ext":"103 RETORNO 1","number_int":"","referen
ce":"","state":"QUERETARO","street":"CANDIDO AVILES","zipcode":"76150"},"cellPho
ne":"","colonia":"CONSTITUYENTES","country":"MEXICO","dateOfJoining":{"date":26,
"day":4,"hours":21,"minutes":37,"month":3,"seconds":42,"time":1335494262977,"tim
ezoneOffset":300,"year":112},"email":"","features":["EXTRA_DATA_IN_CFD"],"id":"X
AXX010101000","localidad":"","municipio":"QUERETARO","name":"SU EMPRESA O PERSON
A FISICA","name_contact":"","nextel":"","nextelId":"","number_ext":"103 RETORNO
1","number_int":"","phone1":"","phone2":"","phone3":"","reference":"","rfc":"XAX
X010101000","source":{"address":{"country":"MEXICO","locale":"","municipio":"QUE
RETARO","name":"","neighbourhood":"CONSTITUYENTES","number_ext":"103 RETORNO 1",
"number_int":"","reference":"","state":"QUERETARO","street":"CANDIDO AVILES","zi
pcode":"76150"},"cellPhone":"","email":"","name":"SU EMPRESA O PERSONA FISICA","
phone":"","rfc":"XAXX010101000"},"state":"QUERETARO","street":"CANDIDO AVILES","
type":"FACTURATi","zipcode":"76150"}
2015-02-03 10:32:00,032  INFO [main](EmisorController.java:130) - Type : FACTUR
ATi
2015-02-03 10:32:00,032  INFO [main](EmisorController.java:133) - FEATURES : EX
TRA_DATA_IN_CFD
2015-02-03 10:32:00,038 DEBUG [main](EmisorController.java:75) - Leyenda PDF :
ESTE DOCUMENTO ES UNA REPRESENTACION IMPRESA DE UN CFDI
2015-02-03 10:32:00,338 ERROR [main](FacturaT.java:191) - FILE NOT FOUND : C:\E
SCENARIOS\CFDI\Factura-T.session.last
2015-02-03 10:32:03,808 DEBUG [main](JasperCreatorImpl.java:56) - JASPER DIR Sy
stem/jasper
2015-02-03 10:32:03,862  INFO [main](CFDiWSClient.java:49) - Setting up CFDiWSC
LIENT pointing to TESTING : http://efacturatesta.com:8080/FacturaTi
2015-02-03 10:32:04,106 DEBUG [main](JasperCreatorImpl.java:56) - JASPER DIR Sy
stem/jasper
2015-02-03 10:32:04,118 DEBUG [main](JasperCreatorImpl.java:56) - JASPER DIR Sy
stem/jasper
2015-02-03 10:32:04,162 DEBUG [main](ConnectorReader.java:69) - Flat file conne
ctor reader started
2015-02-03 10:32:04,256 DEBUG [main](TaskService.java:49) - Starting task execu
tor suite
2015-02-03 10:32:11,285 DEBUG [main](InvoiceQueryForm.java:167) - lets reloaded
 cfds
Exception in thread "main" org.springframework.beans.factory.BeanCreationExcepti
on: Error creating bean with name 'queryLayout' defined in URL [jar:file:/C:/ESC
ENARIOS/CFDI/Factura-T/System/Jar/FacturaT-9.1.1.jar!/com/facturat/view/form/que
ry/invoice/QueryLayout.class]: Instantiation of bean failed; nested exception is
 org.springframework.beans.BeanInstantiationException: Could not instantiate bea
n class [com.facturat.view.form.query.invoice.QueryLayout]: Constructor threw ex
ception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.ConstructorResolver.autowir
eConstructor(ConstructorResolver.java:288)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1035)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:939)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:485)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBean(AbstractAutowireCapableBeanFactory.java:456)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getOb
ject(AbstractBeanFactory.java:294)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
y.getSingleton(DefaultSingletonBeanRegistry.java:225)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
an(AbstractBeanFactory.java:291)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
(AbstractBeanFactory.java:193)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.
preInstantiateSingletons(DefaultListableBeanFactory.java:609)
        at org.springframework.context.support.AbstractApplicationContext.finish
BeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refres
h(AbstractApplicationContext.java:469)
        at com.facturat.view.FacturaT.loadContext(FacturaT.java:89)
        at com.facturat.view.FacturaT.<init>(FacturaT.java:49)
        at com.facturat.view.FacturaT.main(FacturaT.java:206)
Caused by: org.springframework.beans.BeanInstantiationException: Could not insta
ntiate bean class [com.facturat.view.form.query.invoice.QueryLayout]: Constructo
r threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:1
62)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy
.instantiate(SimpleInstantiationStrategy.java:110)
        at org.springframework.beans.factory.support.ConstructorResolver.autowir
eConstructor(ConstructorResolver.java:280)
        ... 14 more
Caused by: java.lang.NullPointerException
        at com.facturat.view.table.TableHelper.getClients(TableHelper.java:198)
        at com.facturat.view.form.query.invoice.InvoiceQueryForm.setupModel(Invo
iceQueryForm.java:170)
        at com.facturat.view.form.query.invoice.InvoiceQueryForm.<init>(InvoiceQ
ueryForm.java:159)
        at com.facturat.view.form.query.invoice.QueryLayout.<init>(QueryLayout.j
ava:43)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

```
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
```

orAccessorImpl.java:39)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:1
47)
        ... 16 more
2015-02-03 10:32:24,174 DEBUG [pool-5-thread-1](ConnectorReader.java:115) - FLA
T FILE CONNECTOR IS NOT ENABLED

**Comment by RigoFlores** [comment]
Intenté con una BD limpia, y tampoco levantó...

**Comment by RigoFlores** [comment]
OK, si quedó y en el XML no incluye los caracteres raros. Así debería estar en web también.
