### ISSUE TITLE
Agregar nodo Currency en addenda Liverpool

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#321]
Aplica para escritorio.
Se puede agregar un dato extra adicional para mostrar el currencyFunction, o si es mas rápido se puede dejar fijo a BILLING_CURRENCY
La moneda y el tipo de cambio se toma del XML estándar.

**Comment by jccastillo0007** [comment]
Done... release 9.1.2 de jenkins : http://188.166.59.163:8080/job/FacturaT/

**Comment by RigoFlores** [comment]
NO LEVANTA, MARCA EL SIG ERROR. EL RELEASE ANTERIOR EN EL JENKINS TAMPOCO JALÓ...
2015-02-12 14:37:54,855 DEBUG [main](FacturaT.java:134) - Initializing FacturaT

2015-02-12 14:37:54,971 DEBUG [main](EmisorController.java:46) - we found the k
ey : facturaT_TTA060126MH4.cfdi
2015-02-12 14:37:55,055  INFO [main](EmisorController.java:113) - JSON KEY :{"a
ddress":{"country":"MEXICO","locale":"","municipio":"GUSTAVO A. MADERO","name":"
","neighbourhood":"EL COYOL","number_ext":"10-EDIF. J PH3","number_int":"","refe
rence":"","state":"DISTRITO FEDERAL","street":"ORIENTE 157","zipcode":"07420"},"
cellPhone":"","colonia":"EL COYOL","country":"MEXICO","dateOfJoining":{"date":10
,"day":1,"hours":20,"minutes":34,"month":2,"seconds":25,"time":1394505265988,"ti
mezoneOffset":360,"year":114},"email":"","features":["EXTRA_DATA_IN_CFD","ADDEND
AS","COMPLEMENTO_LIVERPOOL"],"id":"TTA060126MH4","localidad":"","municipio":"GUS
TAVO A. MADERO","name":"TACSA, TECNOLOGIA AGROINDUSTRIA Y CAPACITACION, S.A. DE
C.V.","name_contact":"","nextel":"","nextelId":"","number_ext":"10-EDIF. J PH3",
"number_int":"","phone1":"","phone2":"","phone3":"","reference":"","rfc":"TTA060
126MH4","source":{"address":{"country":"MEXICO","locale":"","municipio":"GUSTAVO
 A. MADERO","name":"","neighbourhood":"EL COYOL","number_ext":"10-EDIF. J PH3","
number_int":"","reference":"","state":"DISTRITO FEDERAL","street":"ORIENTE 157",
"zipcode":"07420"},"cellPhone":"","email":"","name":"TACSA, TECNOLOGIA AGROINDUS
TRIA Y CAPACITACION, S.A. DE C.V.","phone":"","rfc":"TTA060126MH4"},"state":"DIS
TRITO FEDERAL","street":"ORIENTE 157","type":"FACTURATi","zipcode":"07420"}
2015-02-12 14:37:55,201  INFO [main](EmisorController.java:130) - Type : FACTUR
ATi
2015-02-12 14:37:55,202  INFO [main](EmisorController.java:133) - FEATURES : EX
TRA_DATA_IN_CFD
2015-02-12 14:37:55,203  INFO [main](EmisorController.java:133) - FEATURES : AD
DENDAS
2015-02-12 14:37:55,204  INFO [main](EmisorController.java:133) - FEATURES : CO
MPLEMENTO_LIVERPOOL
2015-02-12 14:37:55,210 DEBUG [main](EmisorController.java:75) - Leyenda PDF :
ESTE DOCUMENTO ES UNA REPRESENTACION IMPRESA DE UN CFDI
2015-02-12 14:37:55,398 ERROR [main](FacturaT.java:191) - FILE NOT FOUND : C:\E
SCENARIOS\ADDENDA_LIVERPOOL\Factura-T.session.last
2015-02-12 14:37:57,966 DEBUG [main](JasperCreatorImpl.java:56) - JASPER DIR Sy
stem/jasper
2015-02-12 14:37:58,018  INFO [main](CFDiWSClient.java:49) - Setting up CFDiWSC
LIENT pointing to TESTING : http://efacturatesta.com:8080/FacturaTi
2015-02-12 14:37:58,263 DEBUG [main](JasperCreatorImpl.java:56) - JASPER DIR Sy
stem/jasper
2015-02-12 14:37:58,275 DEBUG [main](JasperCreatorImpl.java:56) - JASPER DIR Sy
stem/jasper
2015-02-12 14:37:58,331 DEBUG [main](ConnectorReader.java:69) - Flat file conne
ctor reader started
2015-02-12 14:37:58,413 DEBUG [main](TaskService.java:49) - Starting task execu
tor suite
2015-02-12 14:38:02,917 DEBUG [main](InvoiceQueryForm.java:167) - lets reloaded
 cfds
Exception in thread "main" org.springframework.beans.factory.BeanCreationExcepti
on: Error creating bean with name 'queryLayout' defined in URL [jar:file:/C:/ESC
ENARIOS/ADDENDA_LIVERPOOL/Factura-T/System/Jar/FacturaT-9.1.2.jar!/com/facturat/
view/form/query/invoice/QueryLayout.class]: Instantiation of bean failed; nested
 exception is org.springframework.beans.BeanInstantiationException: Could not in
stantiate bean class [com.facturat.view.form.query.invoice.QueryLayout]: Constru
ctor threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.ConstructorResolver.autowir
eConstructor(ConstructorResolver.java:288)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1035)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:939)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:485)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBean(AbstractAutowireCapableBeanFactory.java:456)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getOb
ject(AbstractBeanFactory.java:294)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
y.getSingleton(DefaultSingletonBeanRegistry.java:225)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
an(AbstractBeanFactory.java:291)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
(AbstractBeanFactory.java:193)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.
preInstantiateSingletons(DefaultListableBeanFactory.java:609)
        at org.springframework.context.support.AbstractApplicationContext.finish
BeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refres
h(AbstractApplicationContext.java:469)
        at com.facturat.view.FacturaT.loadContext(FacturaT.java:89)
        at com.facturat.view.FacturaT.<init>(FacturaT.java:49)
        at com.facturat.view.FacturaT.main(FacturaT.java:206)
Caused by: org.springframework.beans.BeanInstantiationException: Could not insta
ntiate bean class [com.facturat.view.form.query.invoice.QueryLayout]: Constructo
r threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:1
62)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy
.instantiate(SimpleInstantiationStrategy.java:110)
        at org.springframework.beans.factory.support.ConstructorResolver.autowir
eConstructor(ConstructorResolver.java:280)
        ... 14 more
Caused by: java.lang.NullPointerException
        at com.facturat.view.table.TableHelper.getClients(TableHelper.java:198)
        at com.facturat.view.form.query.invoice.InvoiceQueryForm.setupModel(Invo
iceQueryForm.java:170)
        at com.facturat.view.form.query.invoice.InvoiceQueryForm.<init>(InvoiceQ
ueryForm.java:159)
        at com.facturat.view.form.query.invoice.QueryLayout.<init>(QueryLayout.j
ava:43)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

```
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
```

orAccessorImpl.java:39)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:1
47)
        ... 16 more
2015-02-12 14:38:18,332 DEBUG [pool-5-thread-1](ConnectorReader.java:115) - FLA
T FILE CONNECTOR IS NOT ENABLED

**Comment by RigoFlores** [comment]
igual probé con una BD vacía y tampoco... al parecer el jenkins si le mete ruido...
la cliente es de las chingaquedito, ya marcó para ver cuándo entregamos...

**Comment by jccastillo0007** [comment]
Done....
