### ISSUE TITLE
No cancela un XML cuando no incluye folio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#535]
Es un caso muy extraño entre todos los clientes.
A estos clientes solo les timbramos, y al ser opcionales para el SAT la serie y el folio, ellos no lo incluyen en sus recibos de nómina.
Entonces me pidieron por primera vez que les cancele un XML, y el resultado es que la aplicación siempre espera al menos que el folio exista.
Para cancelar no debe solicitarlo como obligatorio.
OJO, este issue no debe afectar el control de folios cancelados en la aplicación de escritorio ni web.
De hecho este cliente trabaja conector.... podríamos amarrar que cancele sin folio solo por conector o algo similar, si es que este issue le pega al control actual de facturas canceladas.

**Comment by jccastillo0007** [comment]
Fixed.

Los folios locales no tienen nada que ver con los folios o timbres comprados con nosotros.

**Comment by RigoFlores** [comment]
No entendí el comentario de folios locales, pero me queda claro que una cosa es el contador de folios consumidos por nuestros clientes, y otra el consecutivo del folio interno del cliente.
Este fix aplica solo para escritorio o también para web?

**Comment by jccastillo0007** [comment]
Solo escritorio, en web no he checado si puede suceder, tu si?

**Comment by RigoFlores** [comment]
En principio en WEB no debería presentarse el problema, ya que siempre colocamos un folio (y opcionalmente serie).
Podría darse el caso, pero ahí si creo que no es nuestra obligación soportarlo, ya que sería un XML que no es de la casa...

**Comment by RigoFlores** [comment]
Hice la prueba con el XML previamente cancelado, parece que hizo bien el proceso, pero no generó los acuses... aquí el log... que será?

2016-01-14 10:46:43.0087 INFO pool-4-thread-1 com.facturat.controller.flatfile.ConnectorReader  file to be processed : C:\TIMBRADOR\Factura-T_PCC\CONECTOR_PCC\RUJE770227M27_28dic2015_121033_timbrado.xml 
2016-01-14 10:46:43.0427 DEBUG pool-4-thread-1 com.facturat.controller.flatfile.Connector2Cancel JASPER DIR to be used : System/jasper 
2016-01-14 10:46:43.0467 DEBUG pool-4-thread-1 com.facturati.ws.util.CFDiHelper regular CFD length : 5941 
2016-01-14 10:46:43.0487 DEBUG pool-4-thread-1 com.facturati.ws.util.CFDiHelper zip CFD length : 3092 
2016-01-14 10:46:43.0487 DEBUG pool-4-thread-1 com.facturati.ws.util.CFDiHelper decode CFD length : 4124 
2016-01-14 10:46:43.0487 DEBUG pool-4-thread-1 com.facturati.ws.util.CFDiHelper FacturaTi will get this : EMISOR value : HDM110110UD4 
2016-01-14 10:46:43.0487 DEBUG pool-4-thread-1 com.facturati.ws.util.CFDiHelper FacturaTi will get this : RECEPTOR value : RUJE770227M27 
2016-01-14 10:46:43.0487 DEBUG pool-4-thread-1 com.facturati.ws.util.CFDiHelper FacturaTi will get this : CLIENT_SERIE value : null 
2016-01-14 10:46:43.0487 DEBUG pool-4-thread-1 com.facturati.ws.util.CFDiHelper FacturaTi will get this : CLIENT_FOLIO value : null 
2016-01-14 10:46:43.0487 DEBUG pool-4-thread-1 com.facturati.ws.util.CFDiHelper FacturaTi will get this : SAT_FOLIO value : 9de080ce-a65e-4b2b-9090-9898e52919ba 
2016-01-14 10:46:48.0034 INFO pool-4-thread-1 com.facturati.ws.client.CFDiWSClient FacturaTi ack : com.facturati.ws.binding.jaxb.Ack@1b51e06[code=008,description=CFDi cancelado] 
2016-01-14 10:46:48.0034 DEBUG pool-4-thread-1 com.facturati.ws.client.CFDiWSClient Properties received : ACUSE value : lAaocMR8S9PDMI5q5dvrxVPxvemAx/8IiFtjriDbsqEgAslKEXjIwo6e2blufmiFo9MM9H3nfTrFIUaYvKgaEg== 
2016-01-14 10:46:48.0034 DEBUG pool-4-thread-1 com.facturati.ws.client.CFDiWSClient Properties received : STATUS_PAC value : 201 
2016-01-14 10:46:48.0034 DEBUG pool-4-thread-1 com.facturat.controller.flatfile.Connector2Cancel Cancel process result : 008 description : CFDi cancelado 
2016-01-14 10:46:48.0034 DEBUG pool-4-thread-1 com.facturat.controller.flatfile.Connector2Cancel Propety received : ACUSE value : lAaocMR8S9PDMI5q5dvrxVPxvemAx/8IiFtjriDbsqEgAslKEXjIwo6e2blufmiFo9MM9H3nfTrFIUaYvKgaEg== 
2016-01-14 10:46:48.0034 DEBUG pool-4-thread-1 com.facturat.controller.flatfile.Connector2Cancel Propety received : STATUS_PAC value : 201 
2016-01-14 10:46:48.0044 DEBUG pool-4-thread-1 com.facturat.controller.flatfile.Connector2Cancel CFDi cancelado con éxito 
2016-01-14 10:46:48.0044 DEBUG pool-4-thread-1 com.facturat.controller.CFD.jasper.creator.JasperFacturaTi JASPER DIR System/jasper 
2016-01-14 10:46:48.0044 ERROR pool-4-thread-1 com.facturat.controller.flatfile.ConnectorReader java.lang.NumberFormatException: null 
java.lang.NumberFormatException: null
    at java.lang.Integer.parseInt(Integer.java:417)
    at java.lang.Integer.valueOf(Integer.java:554)
    at com.facturat.controller.flatfile.Connector2Cancel.generateFiles(Connector2Cancel.java:116)
    at com.facturat.controller.flatfile.Connector2Cancel.cancel(Connector2Cancel.java:110)
    at com.facturat.controller.flatfile.ConnectorReader.fileAnalyzer(ConnectorReader.java:334)
    at com.facturat.controller.flatfile.ConnectorReader.run(ConnectorReader.java:144)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:204)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)

**Comment by jccastillo0007** [comment]
Ups, un problema acarreado por no traer folio... al momento de generar el PDF trataba de asignar un valor al folio, pero pues pura riata porque viene vacío.

Fixed.
