### ISSUE TITLE
Carta Porte - No timbre cuando se incluye DESCRIPCION DE LA CARGA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#547]
Cuando se incluye el producto DESCRIPCION DE LA CARGA, no timbra la factura.

Recordar el comportamiento de este producto:
a) La información complementaria se envía como dato extra 6 (CORRECTO)
b) Desaparece todo el tema de [PESO/VOLUMEN]=ALGO... (CORRECTO)
c) Para el XML, se envía la información complementaria como descripcion del producto.  (ENTIENDO QUE AQUÍ ES DONDE SE ATORA)... y envía el siguiente mensaje en la consola (ni siquiera llega a incluirse en el log):

2016-02-20 12:13:27,483 DEBUG [pool-4-thread-1](ConnectorReader.java:123) - FLA
T FILE CONNECTOR IS NOT ENABLED
2016-02-20 12:13:59,250 DEBUG [AWT-EventQueue-0](CFDForm.java:498) - lets reloa
ded clients and products.
2016-02-20 12:13:59,252  INFO [AWT-EventQueue-0](FolioService.java:28) - lookin
g for serie : null
2016-02-20 12:13:59,255  INFO [AWT-EventQueue-0](FolioService.java:28) - lookin
g for serie : TEST
2016-02-20 12:13:59,274  INFO [AWT-EventQueue-0](FolioService.java:28) - lookin
g for serie : TEST
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Inde
x: 5, Size: 0
        at java.util.ArrayList.RangeCheck(ArrayList.java:547)
        at java.util.ArrayList.get(ArrayList.java:322)
        at com.facturat.view.form.cfd.CFDForm.getCFD(CFDForm.java:1026)
        at com.facturat.view.form.cfd.CFDForm$4$1.run(CFDForm.java:351)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:646)
        at java.awt.EventQueue.access$000(EventQueue.java:84)
        at java.awt.EventQueue$1.run(EventQueue.java:607)
        at java.awt.EventQueue$1.run(EventQueue.java:605)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessCo
ntrolContext.java:87)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:616)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThre
ad.java:269)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.
java:184)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThre
ad.java:174)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)

```
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)

    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by jccastillo0007** [comment]
Fixed.
