### ISSUE TITLE
Factura-T escritorio - manejar tipo de cambio a 4 dígitos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#869]
Es posible técnicamente con el esquema actual, en caso afirmativo lo que se ocupa es manejar el tipo de cambio a como lo capturen en pantalla. Si son 2,3 o hasta 6 decimales.

O es que a los clientes ya empezaron a pedirles el CFDI 3.2?

**Comment by jccastillo0007** [comment]
pues al parecer si se puede... ya le puse la modificación, puedes checarlo, lo subí al dropbox

**Comment by RigoFlores** [comment]
respuesta: no puedo checarlo... no jala pruebas...:(

**Comment by RigoFlores** [comment]
negativo, le sigue enviando con 2 decimales

**Comment by jccastillo0007** [comment]
crap, la mascara esta a 4 decimales, pero al crear el pdf le deja dos.... y según yo había validadoque si lo hacía... ya me parezco a ti...

**Comment by RigoFlores** [comment]
Ojo, el tipo de cambio generalmente no se muestra en el PDF. Si existe la variable, pero por lo regular no se muestra.
Este issue principalmente se refiere al XML... ok, también enviarlo al PDF con el mismo formato.

**Comment by jccastillo0007** [comment]
done... creo que se lo habia puesto a la generación de web y no de standalone chiaaaa

**Comment by RigoFlores** [comment]
Yo creo que no se entienden correctamente las peticiones.
Se solicitó el tipo de cambio, y de repente veo que muchas otras cifras se presentan en 4 decimales.
La petición es SOLAMENTE PARA TIPO DE CAMBIO.

De cualquier manera sigue sin jalar. Marca error...
mx/TimbreFiscalDigital http://www.sat.gob.mx/TimbreFiscalDigital/TimbreFiscalDig
ital.xsd"/>
    </cfdi:Complemento>
</cfdi:Comprobante>
2017-01-26 11:37:57,982 DEBUG [AWT-EventQueue-0] (BarCodeGenerator.java:83) - CB
B : ?re=ACO560518KW7&rr=CEC090804EI9&tt=0000017500.003600&id=1B52F1BA-261E-4685-
9BA3-8CFFA971AC9B
2017-01-26 11:37:58,314 ERROR [AWT-EventQueue-0] (FacturaTiCreator.java:1204) -
java.lang.IllegalArgumentException: Cannot format given Object as a Number
java.lang.IllegalArgumentException: Cannot format given Object as a Number
        at java.text.DecimalFormat.format(DecimalFormat.java:486)
        at java.text.Format.format(Format.java:140)
        at com.facturat.controller.CFD.jasper.JasperCFDBean.<init>(JasperCFDBean
.java:479)
        at com.facturat.controller.CFD.creator.FacturaTiCreator.getJasperPrint(F
acturaTiCreator.java:304)
        at com.facturat.controller.CFD.creator.FacturaTiCreator.createCFD(Factur
aTiCreator.java:218)
        at com.facturat.controller.CFD.creator.FacturaTiCreator.createCFD(Factur
aTiCreator.java:1149)
        at com.facturat.view.form.cfd.CFDForm$4$1.run(CFDForm.java:351)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:646)
        at java.awt.EventQueue.access$000(EventQueue.java:84)
        at java.awt.EventQueue$1.run(EventQueue.java:607)
        at java.awt.EventQueue$1.run(EventQueue.java:605)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessCo
ntrolContext.java:87)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:616)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThre
ad.java:269)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.
java:184)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThre
ad.java:174)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)

        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)

        at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
2017-01-26 11:37:59,533  INFO [AWT-EventQueue-0] (FolioService.java:28) - lookin
g for serie : FE

**Comment by jccastillo0007** [comment]
Los cambios realizados fueron solo para el tipo de cambio.
Cuando dices "de repente veo que muchas otras cifras se presentan en 4 decimales."  confio en que viste bien, sin embargo, a mi no me dice nada.
El error que marca es de hecho porque se estaba tratando de enviar al PDF con los 4 decimales también.

**Comment by jccastillo0007** [comment]
Te mando por correo un xml y pdf generado con el tipo de cambio solicitado.
